apiVersion: v1
data:
  config.yaml: |
    rules:
    - metricsQuery: sum(rate(nginx_http_requests_total{job="nginx"}[1m])) by (pod)
      name:
        as: nginx_http_requests_total
        matches: nginx_http_requests_total
      resources:
        template: <<.Resource>>
      seriesQuery: nginx_http_requests_total{job="nginx"}
    - metricsQuery: sum(rate(nginx_http_requests_total{job="nginx2"}[1m])) by (pod)
      name:
        as: nginx_http_requests_total2
        matches: nginx_http_requests_total
      resources:
        template: <<.Resource>>
      seriesQuery: nginx_http_requests_total{job="nginx2"}
kind: ConfigMap
metadata:
  annotations:
    meta.helm.sh/release-name: prometheus-adapter
    meta.helm.sh/release-namespace: monitoring
  creationTimestamp: "2024-12-27T15:26:58Z"
  labels:
    app.kubernetes.io/component: metrics
    app.kubernetes.io/instance: prometheus-adapter
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: prometheus-adapter
    app.kubernetes.io/part-of: prometheus-adapter
    app.kubernetes.io/version: v0.12.0
    helm.sh/chart: prometheus-adapter-4.11.0
  name: prometheus-adapter
  namespace: monitoring
  resourceVersion: "86236"
  uid: 1c2b8f09-5ed2-49fe-bee2-2c5e3260f9b1
