apiVersion: v1
kind: Namespace
metadata:
  labels:
    kubernetes.io/metadata.name: hpap
  name: hpap
spec:
  finalizers:
  - kubernetes
status:
  phase: Active
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: hpap
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest  # Using the official Nginx image
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "128Mi"   # Request 128Mi of memory
            cpu: "100m"       # Request 100m CPU (0.1 CPU)
          limits:
            memory: "256Mi"   # Limit memory usage to 512Mi
            cpu: "200m"       # Limit CPU usage to 500m (0.5 CPU)
        volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
      - name: nginx-prometheus-exporter
        image: nginx/nginx-prometheus-exporter:latest
        ports:
          - containerPort: 9113
        env:
          - name: NGINX_STATUS_URL
            value: "http://localhost/nginx_status"
      volumes:
        - name: nginx-config
          configMap:
            name: nginx-config
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: hpap
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: http
    - name: nginx-exporter
      port: 9113
      targetPort: 9113
  type: LoadBalancer  # You can also use NodePort or ClusterIP depending on your setup
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: nginx-hpa
  namespace: hpap
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nginx-deployment  # The name of the nginx deployment
  minReplicas: 1            # The minimum number of Pods
  maxReplicas: 5            # The maximum number of Pods
  metrics:
  - type: External
    external:
      metric:
        name: http_requests_total
        selector:
          matchLabels:
            app: nginx  # Replace with your app's label for custom metrics
      target:
        type: Value
        value: "1000"  # Scale when total HTTP requests exceed 2000